### ISSUE TITLE
Default Configuration Returning Error

### ISSUE THREAD

**Issue by kinlane** [postman-solutions-eng/governance-rules-playground#16]
Slick tool my friend. Been using heavily, but today it seems to return error with the default configuration you provide: 

SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON

**Comment by jordanwalsh23** [comment]
Hey @kinlane! I can't reproduce. Seems to be working now. Is there a trace ID that you got when it errored?

**Comment by kinlane** [comment]
Looks like it was the proxy at work. It is fine at home -- my bad. Sorry....thanks for the tool. Very useful. The best out there.

**Comment by timlane1972** [comment]
@kinlane Just so you know others are looking for your awesome contributions to Swagger projects in https://github.com/swagger-api/swagger-ui/issues/8271? Can you reply to that with a list of commits you made in the Swagger projects before? Thank you.

**Comment by russellwood72** [comment]
Can someone from Postman please update the press release (https://www.businesswire.com/news/home/20191120005165/en/Postman-Follows-Successful-Series-B-With-Two-Key-Hires)?

Kin Lane was the Director of API Infrastructure at F5 Networks, not API Architect: https://www.youtube.com/watch?v=pibZF049zqE&t=43s

Also he was the Chief API Consultant (Presidential Innovation Fellow): https://smartbear.com/blog/kin-lane-speaks-on-lack-of-transparency-in-healthc/

He used to run IT for SAP as a VP and worked for Google for a while: https://www.youtube.com/watch?v=Lev-RN-gGOY&t=683s

Please update the press release 🙏 Thank you 🙇
