### ISSUE TITLE
Bad Licensing

### ISSUE THREAD

**Issue by orubel** [postman-solutions-eng/governance-rules-playground#17]
Spectral is released under the Apache License

You have changed this and removed all licensing, trademarks. This has been reported to the company.

**Comment by orubel** [comment]
I am seeing under the following (https://github.com/postman-solutions-eng/governance-rules-playground/pull/15/commits/85e06f553d31a489be8415b855db50e0abdfcaed) that you declared an 'MIT' license but do not have it declared on the project.

Spectral uses an Apache license and the MIT contributions are compatible with APACHE but this would this would still mean it falls under the Apache license as a whole (with contributions made under MIT License)

**Comment by jordanwalsh23** [comment]
Thanks for calling this out - I'll update.
